### ISSUE TITLE
Define element-ui version

### ISSUE THREAD

**Issue by DiegoGallegos4** [gbouteiller/nuxt-element-ui#1]
How would you define a newer version of element ui, not the version on the package.json file on the project?

**Comment by cyberz** [comment]
Use element-ui as plugin

`yarn add element-ui@latest`

In plugins/element-ui.js
`import Vue from 'vue'
import Element from 'element-ui'
import locale from 'element-ui/lib/locale/lang/en'

Vue.use(Element, { locale })`

in nuxt.config.js plugins options add

`'~/plugins/element-ui'`

**Comment by gbouteiller** [comment]
Hello @DiegoGallegos4 . Thank you for your interest but, as I switched from Nuxt to Quasar, I don't have the time to maintain this project anymore. Feel free to contact me if you want to take over.
