### ISSUE TITLE
Icons not showing on nuxt build

### ISSUE THREAD

**Issue by DiegoGallegos4** [gbouteiller/nuxt-element-ui#2]
Reproduce
-----------

1. `nuxt build`

2. Server build assets with express (SSR).

Error
-----

Icons not showing

![image](https://user-images.githubusercontent.com/5933437/54074659-ddf7b880-425a-11e9-939c-7c2ba30afbdd.png)

When running `yarn dev` they look just fine. I use the configuration suggested on the README and added Icon on elementUI array

**Comment by gbouteiller** [comment]
Hello @DiegoGallegos4 . Thank you for your interest but, as I switched from Nuxt to Quasar, I don't have the time to maintain this project anymore. Feel free to contact me if you want to take over.
