### ISSUE TITLE
HTMLElement is not defined in Nuxt 2.6.3 / v2.7.0-25937288.3539c64b

### ISSUE THREAD

**Issue by zeidlos** [gbouteiller/nuxt-element-ui#3]
In `node_modules/element-ui/lib/element-ui.common.js` Line 36822, `HTMLElement` returns an undefined, resulting in an error.

Does not happen with Nuxt 2.6.2

**Comment by gbouteiller** [comment]
Hello @zeidlos . Thank you for your interest but, as I switched from Nuxt to Quasar, I don't have the time to maintain this project anymore. Feel free to contact me if you want to take over.
