### ISSUE TITLE
Document how to load required theme or provide as option

### ISSUE THREAD

**Issue by MartinMuzatko** [gbouteiller/nuxt-element-ui#4]
It would be great to be able to have the  nuxt module already load the default theme via an option flag.
Otherwise:  Document how to make this module work with the default theme

**Comment by gbouteiller** [comment]
Hello @MartinMuzatko. Thank you for your interest but, as I switched from Nuxt to Quasar, I don't have the time to maintain this project anymore. Feel free to contact me if you want to take over.
